import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Application",
  description: "Generated by Hritik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          margin: 0,
          padding: 0,
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          backgroundColor: "#f4f4f9",
          fontFamily: "var(--font-geist-sans), sans-serif",
        }}
      >
        {/* Header */}
        <header
          style={{
            backgroundColor: "#0070f3",
            padding: "15px 30px",
            color: "#fff",
            fontSize: "1.5rem",
            fontWeight: "bold",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <div> <Link href="/" style={{ color: "#fff", textDecoration: "none" }}>
              Hritik
            </Link></div>
          <nav style={{ display: "flex", gap: "20px" }}>
            <Link href="/home" style={{ color: "#fff", textDecoration: "none" }}>
              Home
            </Link>
            <Link href="/about" style={{ color: "#fff", textDecoration: "none" }}>
              About
            </Link>
          </nav>
        </header>

        {/* Main content */}
        <main style={{ flex: 1, padding: "40px" }}>{children}</main>

        {/* Footer */}
        <footer
          style={{
            backgroundColor: "#222",
            color: "#fff",
            textAlign: "center",
            padding: "15px",
            fontSize: "0.9rem",
          }}
        >
          © {new Date().getFullYear()} Hritik. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
