import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Application",
  description: "Generated by Hritik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          margin: 0,
          padding: 0,
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          backgroundColor: "#f9fafc", // light neutral background
          fontFamily: "var(--font-geist-sans), sans-serif",
          color: "#1a1a1a",
        }}
      >
        {/* Header */}
        <header
          style={{
            backgroundColor: "#0f172a", // deep navy blue
            padding: "15px 40px",
            color: "#fff",
            fontSize: "1.5rem",
            fontWeight: "bold",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            boxShadow: "0 2px 6px rgba(0,0,0,0.2)",
          }}
        >
          <div>
            <Link
              href="/"
              style={{
                color: "#f97316", // orange accent
                textDecoration: "none",
                fontSize: "1.8rem",
                fontWeight: "bold",
              }}
            >
              Hritik
            </Link>
          </div>
          <nav style={{ display: "flex", gap: "25px" }}>
            <Link
              href="/home"
              style={{
                color: "#e2e8f0",
                textDecoration: "none",
                fontSize: "1rem",
                transition: "color 0.3s",
              }}
            >
              Home
            </Link>
            <Link
              href="/about"
              style={{
                color: "#e2e8f0",
                textDecoration: "none",
                fontSize: "1rem",
                transition: "color 0.3s",
              }}
            >
              About
            </Link>
            <Link
              href="/education"
              style={{
                color: "#e2e8f0",
                textDecoration: "none",
                fontSize: "1rem",
                transition: "color 0.3s",
              }}
            >
              Education
            </Link>
            <Link
              href="/pooja-hegade"
              style={{
                color: "#e2e8f0",
                textDecoration: "none",
                fontSize: "1rem",
                transition: "color 0.3s",
              }}
            >
              Pooja Hegade
            </Link>
          </nav>
        </header>

        {/* Main content */}
        <main
          style={{
            flex: 1,
            padding: "50px",
            maxWidth: "1200px",
            margin: "0 auto",
          }}
        >
          {children}
        </main>

        {/* Footer */}
        <footer
          style={{
            backgroundColor: "#0f172a", // same as header for consistency
            color: "#94a3b8", // soft gray
            textAlign: "center",
            padding: "20px",
            fontSize: "0.95rem",
            borderTop: "1px solid #1e293b",
          }}
        >
          © {new Date().getFullYear()} <span style={{ color: "#f97316" }}>Hritik</span>. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
